[tool.poetry]
name = "educational-app"
version = "0.1.0"
description = "App for school students"
authors = ["Varsha R <varsharamineni@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
