# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false
maxUploadSize = 1024

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"