# .streamlit/config.toml
[server]
headless = true
port = 8501
maxUploadSize = 1024
enableCORS = true  # Allow CORS to make requests to external APIs
enableXsrfProtection = true  # Keep CSRF protection enabled for security

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

