# .streamlit/config.toml
[server]
headless = true
port = 8501
maxUploadSize = 1024
enableCORS = true  # Allow CORS to make requests to external APIs
enableXsrfProtection = true  # Keep CSRF protection enabled for security

#[theme]
#primaryColor = "#F63366"
#secondaryBackgroundColor = "#F0F2F6"
##backgroundColor = "#FFFFFF"
#textColor = "#000000"
#font = "sans serif"

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#292929"
textColor = "#FFFFFF"
#font = "sans serif"
base= 'light'
font='monospace'
